on: 
    push:
        branches:
            - master
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: netcore-gh-actions-as
    AZURE_WEBAPP_PACKAGE_PATH: './publish'
    DOTNET_VERSION: '3.1.x'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # checkout repo
        -   name: Checkout repo
            uses: actions/checkout@master

        -   name: Setup .NET Core
            uses: actions/setup-dotnet@v1
            with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
            
        -   name: dotnet build and publish
            working-directory: ./src/webapp
            run: |
                dotnet restore
                dotnet build --no-restore --configuration Release 
                dotnet publish -c Release -o '$${ env.AZURE_WEBAPP_PACKAGE_PATH}'
   

        -   name: 'Run Azure webapp deploy action using publish profile credentials'
            uses: azure/webapps-deploy@v2
            with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: $${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                package: ./src/webapp/publish



